<?php
declare(strict_types=1);

/**
 * See LICENSE.md file for further details.
 */

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\FanChart\Configuration;

/** @var Configuration $configuration */
/** @var string $title */
/** @var string $moduleName */
/** @var Individual $individual */
/** @var Tree $tree */
/** @var array $chartParams */
/** @var string $javascript */
/** @var string $stylesheet */
/** @var string $ajaxUrl */
?>

<div id="page-fan">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <form id="webtrees-fan-chart-form" method="post" class="wt-page-options wt-page-options-fan-chart d-print-none">
        <?= csrf_field() ?>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
                <?= I18N::translate('Individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select-individual', [
                        'id'         => 'xref',
                        'name'       => 'xref',
                        'individual' => $individual,
                        'tree'       => $tree,
                        'required'   => true,
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="fanDegree">
                <?= I18N::translate('Layout') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select', [
                        'id'       => 'fanDegree',
                        'name'     => 'fanDegree',
                        'selected' => $configuration->getFanDegree(),
                        'options'  => $configuration->getFanDegreeList(),
                        'class'    => 'form-control-sm',
                    ])
                ?>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
                <?= I18N::translate('Generations') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select', [
                        'id'       => 'generations',
                        'name'     => 'generations',
                        'selected' => $configuration->getGenerations(),
                        'options'  => $configuration->getGenerationsList(),
                        'class'    => 'form-control-sm',
                    ])
                ?>
            </div>
        </div>

        <div class="collapse<?= ($configuration->getShowMore() ? ' show' : '') ?>" id="showMoreOptions">
            <div class="form-group row">
                <label class="col-form-label col-sm-3 wt-page-options-label">
                    <?= I18N::translate('Presentation') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?=
                        view('components/checkbox', [
                            'id'      => 'hideEmptySegments',
                            'name'    => 'hideEmptySegments',
                            'label'   => I18N::translate('Hide empty segments'),
                            'checked' => $configuration->getHideEmptySegments(),
                        ])
                    ?>

                    <?=
                        view('components/checkbox', [
                            'id'      => 'showColorGradients',
                            'name'    => 'showColorGradients',
                            'label'   => I18N::translate('Show color gradients'),
                            'checked' => $configuration->getShowColorGradients(),
                        ])
                    ?>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="innerArcs">
                    <?= I18N::translate('Number of inner circles') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?=
                        view('components/select', [
                            'id'       => 'innerArcs',
                            'name'     => 'innerArcs',
                            'selected' => $configuration->getInnerArcs(),
                            'options'  => $configuration->getInnerArcsList(),
                            'class'    => 'form-control-sm',
                        ])
                    ?>
                    <small class="form-text text-muted">
                        <?= I18N::translate('Specifies the number of circles in which the text is written along a arc.') ?>
                    </small>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="fontScale">
                    <?= I18N::translate('Font size') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <div class="input-group input-group-sm">
                        <input class="form-control" type="text" name="fontScale" id="fontScale"
                               maxlength="3" placeholder="100" value="<?= $configuration->getFontScale() ?>">
                        <div class="input-group-append">
                            <span class="input-group-text">%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12 wt-page-options-value text-center">
                <div class="btn-group-sm float-left more">
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#showMoreOptions" aria-expanded="false" aria-controls="showMoreOptions">
                        <?= I18N::translate('More options ...') ?>
                    </button>
                </div>

                <div class="btn-group-sm">
                    <input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
                    <input class="btn btn-primary" type="button" value="<?= I18N::translate('reset') ?>" id="resetButton">
                </div>
            </div>
        </div>
    </form>

    <div class="row">
        <div id="fan_chart" class="wt-ajax-load wt-page-content wt-chart wt-fan-chart"></div>
    </div>
</div>

<?php View::push('styles') ?>
<link rel="stylesheet" href="<?= e($stylesheet) ?>">
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<script>

// Wait for DOM to be ready
document.addEventListener("DOMContentLoaded", function () {
    // Set up storage object
    let storage = new WebtreesFanChart.Storage("webtrees-fan-chart");

    // Register all form elements valid for storing data
    storage.register("fanDegree");
    storage.register("generations");
    storage.register("hideEmptySegments");
    storage.register("showColorGradients");
    storage.register("innerArcs");
    storage.register("fontScale");

    // Handle special case with option toggler
    $("#showMoreOptions")
        .on("shown.bs.collapse", function () {
            storage.write("showMoreOptions", true);
        })
        .on("hidden.bs.collapse", function () {
            storage.write("showMoreOptions", false);
        })
        .collapse(
            storage.read("showMoreOptions") ? "show" : "hide"
        );


    let data    = <?= $chartParams ?>;
    let ajaxUrl = <?= json_encode($ajaxUrl) ?>;

    // Create chart instance with stored configuration
    const fanChart = new WebtreesFanChart.FanChart(
        "#fan_chart",
        {
            labels            : data.labels,
            generations       : parseInt(storage.read("generations")),
            fanDegree         : parseInt(storage.read("fanDegree")),
            defaultColor      : data.defaultColor,
            fontScale         : parseInt(storage.read("fontScale")),
            fontColor         : data.fontColor,
            hideEmptySegments : storage.read("hideEmptySegments"),
            showColorGradients: storage.read("showColorGradients"),
            rtl               : data.rtl,
            innerArcs         : parseInt(storage.read("innerArcs"))
        }
    );

    // Load initial chart data
    $.getJSON(
        getUrl(ajaxUrl),
        function (data) {
            fanChart.draw(data);

            // document.getElementById("fan_chart")
            //     .scrollIntoView(true);
        }
    );

    // Redraw chart upon form submit
    $("#webtrees-fan-chart-form").on("submit", function (event) {
        event.preventDefault();

        // Update configuration with changed form values
        fanChart.configuration.generations          = parseInt(document.getElementById('generations').value);
        fanChart.configuration.fanDegree            = parseInt(document.getElementById('fanDegree').value);
        fanChart.configuration.fontScale            = parseInt(document.getElementById('fontScale').value);
        fanChart.configuration.hideEmptySegments    = !!document.getElementById('hideEmptySegments').checked;
        fanChart.configuration.showColorGradients   = !!document.getElementById('showColorGradients').checked;
        fanChart.configuration.numberOfInnerCircles = parseInt(document.getElementById('innerArcs').value);

        $.getJSON(
            getUrl(ajaxUrl),
            function (data) {
                fanChart.draw(data);

                // document.getElementById("fan_chart")
                //     .scrollIntoView(true);
            }
        );
    });

    /**
     * Returns the AJAX update URL.
     *
     * @returns {string}
     */
    function getUrl(baseUrl)
    {
        var url = new URL(baseUrl);
        url.searchParams.set("xref", document.getElementById('xref').value);
        url.searchParams.set("generations", fanChart.configuration.generations);

        return url.toString();
    }
});

</script>
<?php View::endpush(); ?>
