<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\FanChart\Configuration;

/**
 * @var Configuration $configuration
 */
?>

<div class="row">
    <label class="col-sm-3 col-form-label wt-page-options-label" for="detailedDateGenerations">
        <?= I18N::translate('Birth and death date precision') ?>
    </label>
    <div class="col-sm-9 wt-page-options-value">
        <?=
            view('components/select', [
                'name'     => 'detailedDateGenerations',
                'selected' => $configuration->getDetailedDateGenerations(),
                'options'  => $configuration->getDetailedDateGenerationsList(),
                'class'    => 'form-control-sm',
            ])
        ?>
        <small class="form-text text-muted">
            <?= I18N::translate('Show full birth and death dates for early generations to match marriage date precision.') ?>
        </small>
    </div>
</div>
