<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\FanChart\Configuration;

/**
 * @var string        $moduleName
 * @var Configuration $configuration
 */
?>

<?= view($moduleName . '::modules/components/range-slider', [
    'id'     => 'fanDegree',
    'label'  => I18N::translate('Fan size'),
    'value'  => $configuration->getFanDegree(),
    'min'    => 180,
    'max'    => 360,
    'step'   => 5,
    'suffix' => '°',
]) ?>
