<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\FanChart\Configuration;

/**
 * @var string        $moduleName
 * @var Configuration $configuration
 */
?>

<?= view($moduleName . '::modules/components/range-slider', [
    'id'          => 'innerArcs',
    'label'       => I18N::translate('Number of inner levels'),
    'value'       => $configuration->getInnerArcs(),
    'min'         => 0,
    'max'         => 5,
    'description' => I18N::translate('Specifies the number of levels in which the text is written along an arc.'),
]) ?>
