<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use MagicSunday\Webtrees\DescendantsChart\Configuration;

/**
 * @var Configuration $configuration
 * @var string        $moduleName
 */
?>

<div class="btn-toolbar justify-content-end">
    <div class="btn-group">
        <?= view($moduleName . '::modules/components/buttonbar/fullscreen-button') ?>
        <?= view($moduleName . '::modules/components/buttonbar/center-button') ?>
    </div>
    <?php if (($configuration->getHidePngExport() === false) || ($configuration->getHideSvgExport() === false)): ?>
        <div class="btn-group ms-2">
            <?php if ($configuration->getHidePngExport() === false): ?>
                <?= view($moduleName . '::modules/components/buttonbar/png-export-button') ?>
            <?php endif; ?>
            <?php if ($configuration->getHideSvgExport() === false): ?>
                <?= view($moduleName . '::modules/components/buttonbar/svg-export-button') ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php /*
    <?= view($moduleName . '::modules/components/buttonbar/help-button') ?>
 */ ?>
</div>

<script>

// Hide fullscreen button if fullscreen mode is not available (e.g., iPhone)
if (!document.fullscreenEnabled) {
    document
        .querySelector(".webtrees-fan-fullscreen-container .btn-fullscreen")
        .style
        .display = 'none';
}

</script>
