<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\FanChart\Configuration;

/**
 * @var string        $javascript
 * @var Configuration $configuration
 * @var array         $id                The unique chart ID
 * @var array         $chartParams
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var array         $data              The chart data
 */
?>

<div class="webtrees-fan-chart-container" id="webtrees-fan-chart-container-<?= $id ?>"></div>

<?php View::push('javascript'); ?>
<script type="module">

import(<?= json_encode($javascript) ?>).then(({ FanChart }) => {
    const opts = (typeof WebtreesFanChart !== "undefined" && WebtreesFanChart.chartOptions) || {};

    new FanChart(
        "#webtrees-fan-chart-container-<?= $id ?>",
        {
            labels: <?= json_encode($chartParams['labels']) ?>,
            rtl: <?= json_encode($chartParams['rtl']) ?>,
            cssFiles: <?= json_encode($exportStylesheets) ?>,

            get generations() {
                return opts.generations ?? <?= $configuration->getGenerations() ?>;
            },

            get fanDegree() {
                return opts.fanDegree ?? <?= json_encode($configuration->getFanDegree()) ?>;
            },

            get fontScale() {
                return opts.fontScale ?? <?= json_encode($configuration->getFontScale()) ?>;
            },

            get hideEmptySegments() {
                return opts.hideEmptySegments ?? <?= json_encode($configuration->getHideEmptySegments()) ?>;
            },

            get showFamilyColors() {
                return opts.showFamilyColors ?? <?= json_encode($configuration->getShowFamilyColors()) ?>;
            },

            get paternalColor() {
                return opts.paternalColor ?? <?= json_encode($configuration->getPaternalColor()) ?>;
            },

            get maternalColor() {
                return opts.maternalColor ?? <?= json_encode($configuration->getMaternalColor()) ?>;
            },

            get showPlaces() {
                return opts.showPlaces ?? <?= json_encode($configuration->getShowPlaces()) ?>;
            },

            get showParentMarriageDates() {
                return opts.showParentMarriageDates ?? <?= json_encode($configuration->getShowParentMarriageDates()) ?>;
            },

            get innerArcs() {
                return opts.innerArcs ?? <?= json_encode($configuration->getInnerArcs()) ?>;
            },

            get showImages() {
                return opts.showImages ?? <?= json_encode($configuration->getShowImages()) ?>;
            },

            get showNames() {
                return opts.showNames ?? <?= json_encode($configuration->getShowNames()) ?>;
            },

            get showDescendants() {
                return opts.showDescendants ?? <?= json_encode($configuration->getShowDescendants()) ?>;
            },

            showSilhouettes: <?= json_encode($chartParams['showSilhouettes']) ?>,
            nameAbbreviation: <?= json_encode($chartParams['nameAbbreviation']) ?>,
            data: <?= json_encode($data) ?>
        }
    );
});

</script>
<?php View::endpush(); ?>
