<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\FanChart\Configuration;

/**
 * @var string        $javascript
 * @var Configuration $configuration
 * @var array         $id                The unique chart ID
 * @var array         $chartParams
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var array         $data              The chart data
 */
?>

<div class="webtrees-fan-chart-container" id="webtrees-fan-chart-container-<?= $id ?>"></div>

<?php View::push('javascript'); ?>
<script type="module">

import(<?= json_encode($javascript) ?>).then(({ FanChart }) => {
    new FanChart(
        "#webtrees-fan-chart-container-<?= $id ?>",
        {
            labels: <?= json_encode($chartParams['labels']) ?>,
            rtl: <?= json_encode($chartParams['rtl']) ?>,
            cssFiles: <?= json_encode($exportStylesheets) ?>,

            get generations() {
                return (typeof generations !== "undefined" && generations !== null) ? generations : <?= $configuration->getGenerations() ?>
            },

            get fanDegree() {
                return (typeof fanDegree !== "undefined" && fanDegree !== null) ? fanDegree : <?= json_encode($configuration->getFanDegree()) ?>;
            },

            get fontScale() {
                return (typeof fontScale !== "undefined" && fontScale !== null) ? fontScale : <?= json_encode($configuration->getFontScale()) ?>;
            },

            get hideEmptySegments() {
                return (typeof hideEmptySegments !== "undefined" && hideEmptySegments !== null) ? hideEmptySegments : <?= json_encode($configuration->getHideEmptySegments()) ?>;
            },

            get showFamilyColors() {
                return (typeof showFamilyColors !== "undefined" && showFamilyColors !== null) ? showFamilyColors : <?= json_encode($configuration->getShowFamilyColors()) ?>;
            },

            get paternalColor() {
                return (typeof paternalColor !== "undefined" && paternalColor !== null) ? paternalColor : <?= json_encode($configuration->getPaternalColor()) ?>;
            },

            get maternalColor() {
                return (typeof maternalColor !== "undefined" && maternalColor !== null) ? maternalColor : <?= json_encode($configuration->getMaternalColor()) ?>;
            },

            get showPlaces() {
                return (typeof showPlaces !== "undefined" && showPlaces !== null) ? showPlaces : <?= json_encode($configuration->getShowPlaces()) ?>;
            },

            get showParentMarriageDates() {
                return (typeof showParentMarriageDates !== "undefined" && showParentMarriageDates !== null) ? showParentMarriageDates : <?= json_encode($configuration->getShowParentMarriageDates()) ?>;
            },

            get innerArcs() {
                return (typeof innerArcs !== "undefined" && innerArcs !== null) ? innerArcs : <?= json_encode($configuration->getInnerArcs()) ?>;
            },

            get showImages() {
                return (typeof showImages !== "undefined" && showImages !== null) ? showImages : <?= json_encode($configuration->getShowImages()) ?>;
            },

            get showNames() {
                return (typeof showNames !== "undefined" && showNames !== null) ? showNames : <?= json_encode($configuration->getShowNames()) ?>;
            },

            get showDescendants() {
                return (typeof showDescendants !== "undefined" && showDescendants !== null) ? showDescendants : <?= json_encode($configuration->getShowDescendants()) ?>;
            },

            showSilhouettes: <?= json_encode($chartParams['showSilhouettes']) ?>,
            data: <?= json_encode($data) ?>
        }
    );
});

</script>
<?php View::endpush(); ?>
