<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use MagicSunday\Webtrees\FanChart\Configuration;

/**
 * @var array         $id               The unique chart ID
 * @var Configuration $configuration
 * @var string        $title
 * @var string        $moduleName
 * @var Individual    $individual
 * @var Tree          $tree
 * @var array         $chartParams
 * @var string        $javascript
 * @var string[]      $stylesheets
 * @var string[]      $exportStylesheets A list of stylesheets used by SVG export
 * @var string        $ajaxUrl
 */
?>

<div class="webtrees-fan-chart">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <form id="webtrees-fan-chart-form" method="post" class="wt-page-options wt-page-options-fan-chart d-print-none">
        <?= csrf_field() ?>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
                <?= I18N::translate('Individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?=
                    view('components/select-individual', [
                        'name'       => 'xref',
                        'individual' => $individual,
                        'tree'       => $tree,
                        'required'   => true,
                    ])
                ?>
            </div>
        </div>

        <?= view($moduleName . '::modules/fan-chart/form/fan-size', ['configuration' => $configuration]) ?>
        <?= view($moduleName . '::modules/fan-chart/form/generations', ['configuration' => $configuration]) ?>

        <div class="collapse" id="showMoreOptions">
            <?= view($moduleName . '::modules/fan-chart/form/layout', ['configuration' => $configuration, 'moduleName' => $moduleName]) ?>
            <?= view($moduleName . '::modules/fan-chart/form/inner-levels', ['configuration' => $configuration]) ?>
            <?= view($moduleName . '::modules/fan-chart/form/font-size', ['configuration' => $configuration]) ?>
        </div>

        <div class="row mt-3">
            <div class="col-sm-12 wt-page-options-value text-center">
                <div class="btn-toolbar justify-content-between">
                    <div class="btn-group btn-group-sm">
                        <input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
                    </div>

                    <div class="btn-group btn-group-sm">
                        <button id="options"
                                class="btn btn-primary"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#showMoreOptions"
                                aria-expanded="false"
                                aria-controls="showMoreOptions">
                            <span><?= I18N::translate('Show more options') ?></span>
                            <span class="d-none"><?= I18N::translate('Hide more options') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="row webtrees-fan-fullscreen-container">
        <?= view($moduleName . '::modules/components/buttonbar', ['configuration' => $configuration, 'moduleName' => $moduleName]) ?>

        <div id="fan-chart-url" class="wt-ajax-load wt-page-content wt-chart wt-chart-fan mt-0"></div>
    </div>
</div

<?php View::push('styles') ?>
    <?php foreach ($stylesheets as $stylesheet) : ?>
        <link rel="stylesheet" href="<?= e($stylesheet) ?>">
    <?php endforeach ?>
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript) ?>"></script>
<script>

/**
 * Returns the AJAX update URL.
 *
 * @param {String} baseUrl
 * @param {String} generations
 *
 * @returns {String}
 */
function getUrl(baseUrl, generations)
{
    let url = new URL(baseUrl);
    url.searchParams.set("xref", document.getElementById('xref').value);
    url.searchParams.set("generations", generations);

    return url.toString();
}

/**
 * Set visibility of "Show more options" to previous state after page reload.
 * Toggle text on "Show more options" on click.
 *
 * @param {Storage} storage
 */
function toggleMoreOptions(storage)
{
    // Options container
    const showMoreOptions = document.getElementById('showMoreOptions');

    // Options toggle button
    const optionsToggle = document.getElementById('options');

    showMoreOptions.addEventListener('shown.bs.collapse', () => {
        storage.write("showMoreOptions", true);
    });

    showMoreOptions.addEventListener('hidden.bs.collapse', () => {
        storage.write("showMoreOptions", false);
    });

    optionsToggle.addEventListener('click', () => {
        Array.from(optionsToggle.children).forEach((element, index) => {
            element.classList.toggle('d-none');
        });
    });

    if (storage.read("showMoreOptions")) {
        optionsToggle.click()
    }
}

// Set up storage object
const storage = new WebtreesFanChart.Storage("webtrees-fan-chart");

// Register all form elements valid for storing data
storage.register("fanDegree");
storage.register("generations");
storage.register("hideEmptySegments");
storage.register("showColorGradients");
storage.register("showParentMarriageDates");
storage.register("innerArcs");
storage.register("fontScale");

// Handle option toggle button
toggleMoreOptions(storage);

// Set initial stored value for radio button group
document.getElementById("fanDegreeOutput").value = parseInt(storage.read("fanDegree")) + "°";

const fanDegree               = storage.read("fanDegree");
const generations             = parseInt(storage.read("generations"));
const hideEmptySegments       = storage.read("hideEmptySegments");
const showColorGradients      = storage.read("showColorGradients");
const showParentMarriageDates = storage.read("showParentMarriageDates");
const innerArcs               = storage.read("innerArcs");
const fontScale               = storage.read("fontScale");
const ajaxUrl                 = getUrl(<?= json_encode($ajaxUrl) ?>, storage.read("generations"));

document.getElementById("fan-chart-url")
    .setAttribute('data-wt-ajax-url', ajaxUrl);

</script>
<?php View::endpush(); ?>
