<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

/**
 * @var string $block_id
 * @var string $chart_url
 */
?>

<style>
.webtrees-fan-chart-container svg {
    min-height: unset !important;
}
</style>

<div id="chart-block-<?= e($block_id) ?>"></div>

<script>
    $(<?= json_encode('#chart-block-' . $block_id, JSON_THROW_ON_ERROR) ?>).load(<?= json_encode($chart_url, JSON_THROW_ON_ERROR) ?>);
</script>
