<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

/**
 * @var string $block_id
 * @var string $chart_url
 */
?>

<style>
.webtrees-fan-chart-container svg {
    min-height: unset !important;
}
</style>

<div id="chart-block-<?= e($block_id) ?>" data-wt-ajax-url="<?= e($chart_url) ?>">
    <?= view('icons/spinner') ?>
</div>
