<?php

use \Fisharebest\Webtrees\Theme;

/** @var \RSO\WebtreesModule\AncestralFanChart\Controller\Chart $this */

?>

<div id="page-fan">
	<h2 class="wt-page-title"><?php echo $this->getPageTitle() ?></h2>

	<form class="wt-page-options d-print-none" method="get" action="?">
		<input type="hidden" name="ged" value="<?php echo $this->getTree()->getNameHtml() ?>">
		<input type="hidden" name="mod" value="ancestral-fan-chart">

		<fieldset class="form-group">
			<div class="row">
				<label class="col-sm-3 col-form-label wt-page-options-label" for="rootid">
					<?php echo $this->translate('Individual') ?>
				</label>
				<div class="col-sm-9 wt-page-options-value">
					<?php echo $this->printFindIndividualLink() ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group">
			<div class="row">
				<label class="col-sm-3 col-form-label wt-page-options-label" for="fanDegree">
					<?php echo $this->translate('Layout'); ?>
				</label>
				<div class="col-sm-9 wt-page-options-value">
					<?php echo $this->getFanDegreeSelectControl(); ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group">
			<div class="row">
				<label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
					<?php echo $this->translate('Generations'); ?>
				</label>
				<div class="col-sm-9 wt-page-options-value">
					<?php echo $this->getGenerationsInputControl(); ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group">
			<div class="row">
				<label class="col-sm-3 col-form-label wt-page-options-label" for="fontScale">
					<?php echo $this->translate('Font size'); ?>
				</label>
				<div class="col-sm-9 wt-page-options-value">
					<div class="input-group">
						<input class="form-control" type="text" name="fontScale" id="fontScale" size="3" value="<?php echo $this->fontScale; ?>">
						<span class="input-group-addon">%</span>
					</div>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group">
			<div class="row">
				<legend class="col-form-label col-sm-3 wt-page-options-label">
					<?php echo $this->translate('Layout'); ?>
				</legend>
				<div class="col-sm-9 wt-page-options-value">
					<?php echo $this->getHideEmptySegmentsCheckbox(); ?>
					<?php echo $this->getShowColorGradientsCheckbox(); ?>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group">
			<div class="row">
				<div class="col-sm-3 wt-page-options-label"></div>
				<div class="col-sm-9 wt-page-options-value">
					<input class="btn btn-primary" type="submit" value="<?php echo $this->translate('view') ?>">
					<input class="btn btn-primary" type="reset" value="<?php echo $this->translate('reset') ?>">
				</div>
			</div>
		</fieldset>
	</form>

	<div class="row">
		<div id="fan_chart" class="wt-ajax-load wt-page-content wt-chart wt-fan-chart"></div>
	</div>
</div>
