<?php

/**
 * This file is part of the package magicsunday/webtrees-fan-chart.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\View;

/**
 * @var string   $content     The content to output
 * @var string[] $stylesheets The list of stylesheets
 */
?>

<?php echo $content; ?>

<?php View::push('styles'); ?>
<?php foreach ($stylesheets as $stylesheet) { ?>
    <link rel="stylesheet" href="<?php echo e($stylesheet); ?>">
<?php } ?>
<?php View::endpush(); ?>

<?php echo View::stack('styles'); ?>
<?php echo View::stack('javascript'); ?>
