name: i18n

on:
    push:
        branches: [ main, master ]
    pull_request:

permissions:
    contents: read

jobs:
    catalogue:
        uses: magicsunday/.github/.github/workflows/i18n.yml@main
        permissions:
            contents: read
        with:
            check-pipeline: true
